import Head from "next/head";
import React from "react";
import { api } from "@/utils/api";
import type { NextPage } from "next";
import AuthShowcase from "@/components/auth-showcase";
import { Center, Flex } from "@chakra-ui/react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center minH={"100vh"}>
        <Flex direction={"column"} justify={"center"} alignItems={"center"} textAlign={"center"}>
          {hello.data?.greeting}
          <AuthShowcase />
        </Flex>
      </Center>
    </>
  );
};

export default Home;
